### ISSUE TITLE
Read a Promotion

### ISSUE THREAD

**Issue by kylesyx** [nyu-devops-sp22/promotions#10]
**As a** Promotions Manager,
**I need to** be able to read one promotion specified by the promotion_id, including details such as start date or end date,
**So that** we can find any certain items when we want.
   
 ### Details and Assumptions
We may need to use GET to retrieve the data from database.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a promotion_id,
 When a promotion manager wants to retrieve its details and call the read function,
 Then all the details such as start date, end date, promotion id, item id, special term etc will be displayed.
 ```

**Comment by tinay0313** [comment]
read one promotion specified by the promotion_id

**Comment by yaozcoderepo** [comment]
Need to add things like using "GET" method to retrieve specific information

**Comment by yaozcoderepo** [comment]
The assumption section should be more technical about how to implement this "read resource"

**Comment by tinay0313** [comment]
given promotion_id, when I call the read function, I should get back the promotion object identified by promotion_id (so I can know the promotion's details like start/end dates, value, products associated etc.)
