### ISSUE TITLE
Set up initial micro service skeleton

### ISSUE THREAD

**Issue by tinay0313** [nyu-devops-sp22/promotions#2]
**As a** Developer,
 **I need**  a skeleton to start the project,
 **So that** the files are saved in the correct directories that are logically named, and thus easy to access.
   
 ### Details and Assumptions
- See professor's GitHub page for reference: https://github.com/nyu-devops/project-template
- Need a system so that when a code file is created, there is an appropriate directory to store it
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that I am working on the promotions resource,
 When I want to locate a test file,
 Then the file should be stored under the test directory.
 ```

**Comment by tomasort** [comment]
Maybe the acceptance criteria should be that it would need to have a test, and src directory and that it should be ready for us to start working on the project

**Comment by yaozcoderepo** [comment]
Whatever code files we want to create, we should be able to find a directory to add them
