### ISSUE TITLE
UI for Portal Page

### ISSUE THREAD

**Issue by yaozcoderepo** [nyu-devops-sp22/promotions#28]
**As a** eCommerce manager,
 **I need** to know which functions/routes are supported by this microservice and how to navigate to them,
 **So that** I don't have to store URLs for different functions/routes
   
 ### Details and Assumptions
- Add Scenario in the feature file for the portal page
- Scenario should be in Gherkin syntax
- Add UI code for the portal page
- Use Selenium for UI testing
   
 ### Acceptance Criteria  
   
 ```gherkin
Given all the links are set up correctly,
When I click the link to different routes
Then the webpage should be navigated to the corresponding route UI
 ```

**Comment by jh7494** [comment]
Behavior test for UI
