### ISSUE TITLE
Create Database Schemas

### ISSUE THREAD

**Issue by yaozcoderepo** [nyu-devops-sp22/promotions#3]
**As a** Promotions Manager,
**I need** to have a database to persist data of product promotion policies,
**So that** I do not lose the input promotion policies after the server is rebooted.
   
 ### Details and Assumptions
 * We will use PostgreSQL as the persistent store.
 * There should be **one** schema (tables):
    - The first one should have fields including promotionID, promotionName, promotionCode, promotionStartDate, promotionEndDate, promotionType, and description. Here, promotionID is an auto-incrementing (primary) key maintained by the database itself rather than being input by the manager. 
 * The schema should have a foreign key product_id.
 ### Acceptance Criteria  
   
 ```gherkin
 Given I implemented all the required database schemas,
 When a promotion policy is created, updated, or deleted for a product,
 And I reboot the service,
 And I search for the promotion policy for the product,
 Then I should see the change to that product still remains.
 ```

**Comment by tinay0313** [comment]
what fields should we have?
promotion id, promotion name, promotion code, products applied, promotion value

**Comment by tomasort** [comment]
Maybe we should also mention sqlalchemy in this story

**Comment by jh7494** [comment]
We can detail the purpose of IBM Cloud Databases (how does it support our project?).

**Comment by tomasort** [comment]
We could add fields like: promotionID, promotionStartDate, promotionEndDate, promotionType, promotioItemID.

**Comment by tomasort** [comment]
I think we should change this story. For this sprint we don't need to use the cloud, so we should remove that part from the assumptions.

**Comment by yaozcoderepo** [comment]
@tomasort I have removed cloud deployment of the database for this sprint story

**Comment by tomasort** [comment]
@yaozcoderepo Thanks, It will probably be a story in the next sprint; "migrate the db to the cloud" or something.
