### ISSUE TITLE
Query resources by attributes

### ISSUE THREAD

**Issue by jh7494** [nyu-devops-sp22/promotions#32]
**As a** manager
 **I need** to query promotion resources by attributes
 **So that** I can look for some specific resources   
   
 ### Details and Assumptions
 Query resource by product id, start date, end date, type and etc.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I as a manager need to get some specific promotions,
 When I submit filters,
 Then I should receive promotions satisfying provided filters
 ```

**Comment by tinay0313** [comment]
Query by promotion start date?
