### ISSUE TITLE
Add BDD tests to CI

### ISSUE THREAD

**Issue by tomasort** [nyu-devops-sp22/promotions#35]
**As a** Developer
 **I need** to know if a pull requests breaks the BDD tests or not
 **So that** I can be confident that merging a pull requests won't break the build.
   
 ### Details and Assumptions
 * Add bdd.yml to the workflows
 * Ensure that the bdd tests work on Github Actions
 * Add badge to README.md
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that a developer wants to make a new pull request
 When the pull request is entered on github
 Then the BDD tests should run along with the rest of the unit tests on github actions and the code coverage should be recorded.

**Comment by yaozcoderepo** [comment]
I think this story actually overlaps with the "Set up Initial BDD test environment" one

**Comment by jh7494** [comment]
Looks like this is a duplicate?
