### ISSUE TITLE
List Promotions

### ISSUE THREAD

**Issue by yaozcoderepo** [nyu-devops-sp22/promotions#4]
**As a** Promotions Manager
 **I need** to know all products that have at least one promotion policy
 **So that** I can determine which one to buy to save money
   
 ### Details and Assumptions
 * We will send a `GET /promotions` request  to query all products from the promotion product database

   
 ### Acceptance Criteria  
   
 ```gherkin
 When I navigate to the given URL (https://<domain_name>/promotions), 
 Then I should see all the currently promoted products listed,
 And I should also be able to see all the expired and future promotions as well.
 ```

**Comment by jh7494** [comment]
We should list all promotions including expired, ongoing, and scheduled.
