### ISSUE TITLE
Delete a Promotion

### ISSUE THREAD

**Issue by tomasort** [nyu-devops-sp22/promotions#5]
As a Promotions Manager,
I need to be able to remove a specific promotion from the database,
So that we can undo the creation of an incorrect promotion.

### Details and Assumptions
- The inputs for this operation should be a unique promotions ID or the name of a promotion. 
- The delete operation should remove the specified promotion and return a value of true if the promotion is successfully deleted, and false otherwise
- The DELETE http method should be used.

 ### Acceptance Criteria  
   
 ```gherkin
 Given a specific promotion ID
 When a promotion manager makes a call to the Delete method.
 Then the promotion should be deleted from the promotions table.

**Comment by kylesyx** [comment]
Maybe also print the reason why the DELETE action failed.
