### ISSUE TITLE
Create a Promotion

### ISSUE THREAD

**Issue by jh7494** [nyu-devops-sp22/promotions#7]
**As a** Promotions Manager,
 **I need** to create new promotions for one or more products
 **So that** the database persistently stores promotion records.
   
 ### Details and Assumptions
 * Promotions have different types. For example, a promotion can be a discount for a limited time period only or quantity discount.
 * Promotion ID is guaranteed to be unique in database.
 * Promotion value indicates percent off.
 * Each promotion record has a start date. End date can be null if this promotion never ends.
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a product is supposed to be sold on sale,
 When a promotion manager creates a promotion for this product and provides information how this product to be sold (percent off)
 Then a promotion record with specified fields (promotion value, start date, end date, etc.) appears in database.
 ```

**Comment by tomasort** [comment]
We should probably write down what is required to create a new promotion. This could be added to the details and assumptions.

**Comment by yaozcoderepo** [comment]
The "so that" section should better be modified to other aspects

**Comment by tinay0313** [comment]
What fields should we have for a promotion object? Promotion_id, promotion_type, promotion_value, associated_products?

**Comment by kylesyx** [comment]
Start_date, end_date

**Comment by yaozcoderepo** [comment]
When we create a duplicate promotion policy, the backend should report an error about it.
