### ISSUE TITLE
Update a Promotion

### ISSUE THREAD

**Issue by tinay0313** [nyu-devops-sp22/promotions#8]
**As a** Promotions Manager,
 **I need** to be able to update the promotion detail and contents,
 **So that** updates to the promotion event can be reflected correctly. 
   
 ### Details and Assumptions
- will use the "PUT" method
- PUT /promotions/123 will update the Promotion with ID 123
- return 200 OK if the resource is accessed or modified successfully
- result is returned as JSON

 ### Acceptance Criteria  
   
 ```gherkin
 Given a specific promotion_id
 When a promotion manager changes the promotion_value
 Then the updated result as JSON with the updated promotion_value are returned.
 ```

**Comment by jh7494** [comment]
We should use promotion ID to specify which promotion to be updated.
